# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-XS-Queue-Array
version:      0.002
version_from: Array.pm
installdirs:  site
requires:
    POE:                           0.29

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
